### ISSUE TITLE
Hot to use this plugin?

### ISSUE THREAD

**Issue by YUHAI0** [pank-su/fleetmacs#4]

**Comment by pank-su** [comment]
Now, we wait next fleet release, because it will have official emacs keymap plugin. 
If you want to use now, you just can use this version https://github.com/pank-su/fleetmacs/commit/aa9dbd8ca982d98ee40b0d1b669ecac0b1b42dc7.

**Comment by pank-su** [comment]
## Installation 
For install this keymap, just copy [this file](https://github.com/pank-su/fleetmacs/blob/main/fleetmacs-plugin/frontendImpl/src/jvmMain/resources/fleetmacs.json) to Fleet's keymap location.
| **System** | **Path**                                                         |
|------------|------------------------------------------------------------------|
| Windows    | `~\AppData\Roaming\JetBrains\Fleet\keymap\user.json`             |
| Linux      | `~/.config/JetBrains/Fleet/keymap/user.json`                     |
| macOS      | `~/Library/Application Support/Jetbrains/Fleet/keymap/user.json` |
